Revert "Simplify algorithm input widget sub-widget hiding (#232)" (#241)
This reverts commit 5c7c514c0d8e1d60c4840c210d086d7c1fddc059.

Commit 5c7c514c0d8e1d60c4840c210d086d7c1fddc059 introduced the following
error at runtime:

```python
AttributeError: 'visibility' does not exist on QLabel and creating new attributes on C++ objects is not allowed
```

This is caused by replacing .hide() / .show() calls with assignment to a
non-existent .visibility attribute on Qt widgets. Since these are
C++-backed objects, arbitrary attribute creation is not allowed.